version: '3'

services:
  redis-compose:
    image: redis
    command: redis-server --requirepass redis --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /usr/Redis:/var/lib/postgresql/data